version: '3'
services:
  liverpool-db:
    container_name: orders_database
    image: postgres:16.3
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nano3110
      - POSTGRES_DB=liverdb